# Generated by Django 6.0.1 on 2026-06-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_payment_paypal_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='fuel',
            field=models.CharField(choices=[('included', 'Included'), ('excluded', 'Ecluded')], default='included', max_length=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='dropoff_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_rentals', to='rental.branch'),
        ),
        migrations.AddField(
            model_name='rental',
            name='pickup_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_rentals', to='rental.branch'),
        ),
    ]
