# Generated by Django 6.0.1 on 2026-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('cash', 'Cash')], max_length=50),
        ),
    ]
