# Generated by Django 6.0.1 on 2026-06-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_branch_rental_fuel_rental_dropoff_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('included', 'Included'), ('excluded', 'Ecluded')], default='included', max_length=10),
        ),
    ]
