# Generated by Django 6.0.1 on 2026-06-04 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_car_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='rental.branch'),
        ),
    ]
