# Generated by Django 6.0.1 on 2026-06-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_car_current_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='rental.branch'),
        ),
    ]
