# Generated by Django 6.0.1 on 2026-01-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
